name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate manifest.json
      run: |
        if [ ! -f "manifest.json" ]; then
          echo "Error: manifest.json not found"
          exit 1
        fi
        
        # Check if manifest.json is valid JSON
        python3 -m json.tool manifest.json > /dev/null
        echo "✅ manifest.json is valid JSON"
    
    - name: Check required files
      run: |
        required_files=("manifest.json" "background.js" "content.js" "popup.html" "popup.css" "popup.js")
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "❌ Required file missing: $file"
            exit 1
          fi
        done
        echo "✅ All required files present"
    
    - name: Validate HTML
      run: |
        if command -v tidy &> /dev/null; then
          tidy -q -e popup.html || echo "⚠️ HTML validation warnings (non-critical)"
        else
          echo "ℹ️ HTML tidy not available, skipping HTML validation"
        fi
    
    - name: Check file sizes
      run: |
        echo "📊 File sizes:"
        ls -lh manifest.json background.js content.js popup.html popup.css popup.js 